import { City } from './city.model';

/** Ausgewählte Städte im deutschen Bundesland Hessen. */
export const CITIES: City[] = [
  {
    name: 'Frankfurt am Main',
    lat: 50.1109,
    lng: 8.6821,
    image1: 'assets/rasierer.png',
    image1Text: 'Elektrohersteller Braun, Elektrorasierer „Braun S50“, 1950, BraunSammlung, © BRAUN P&G, Braun Archiv Kronberg.',
    image1Source: 'https://www.made-in-hessen.online/braun-2',
    image2: 'assets/radio.png',
    image2Text: 'Elektrohersteller Braun, Radio-Phono-Kombination „Braun SK 5“, 1958, BraunSammlung, © BRAUN P&G, Braun Archiv Kronberg.',
    image2Source: 'https://www.made-in-hessen.online/braun-2',
    image3: 'assets/küchengerät.png',
    image3Text: 'Elektrohersteller Braun, Küchenmaschine „KM 3“, 1954, BraunSammlung, © BRAUN P&G, Braun Archiv Kronberg.',
    image3Source: 'https://www.made-in-hessen.online/braun-2',
    image4: '',
    image4Text: '',
    image4Source: '',
    description: 'NOCH AUSSTEHEND',
  },
  {
    name: 'Offenbach am Main',
    lat: 50.0956,
    lng: 8.7761,
    image1: 'assets/offenburg.png',
    image1Text: 'FAZ, HfG Offenbach, Fotografie, © Frankfurter Allgemeine Zeitung GmbH 2001–2026.',
    image1Source: 'https://www.faz.net/aktuell/rhein-main/region-und-hessen/hfg-offenbach-aerger-um-die-gleichstellung-15781491.html',
    image2: 'assets/Bahn voyage.png',
    image2Text: 'Steffen Reiter, Bahn Voyage, 2013, Modell, HfG Offenbach.',
    image2Source: 'https://www.hfg-offenbach.de/de/pages/design#ueber',
    image3: 'assets/Böx.png',
    image3Text: 'Constanze Leuchtmann, Böx, 2013, Modell, HfG Offenbach.',
    image3Source: 'https://www.hfg-offenbach.de/de/pages/design#ueber',
    image4: 'assets/gerät.png',
    image4Text: 'Tina Blau, Extrusionsschweißgerät, 2013, Modell, HfG Offenbach.',
    image4Source: 'https://www.hfg-offenbach.de/de/pages/design#ueber',
    description: '',
  },
  {
    name: 'Kassel',
    lat: 51.3127,
    lng: 9.4797,
    image1: 'assets/parkscheibe.png',
    image1Text: 'Wikipedia, Parkscheibe (Bild 291 StVO), in: Verkehrsblatt Nr. 237 vom 24. November 1981, S. 447.',
    image1Source: 'https://de.wikipedia.org/wiki/Parkscheibe',
    image2: '',
    image2Text: '',
    image2Source: '',
    image3: '',
    image3Source: '',
    image4: '',
    image4Source: '',
    description: 'TEXT PARKSCHEIBE',
  },
  {
    name: 'Darmstadt',
    lat: 49.8728,
    lng: 8.6512,
    image1: 'assets/altesbild.png',
    image1Text: 'O. A., Werkansicht der Röhm & Haas AG (1920), © Evonik Industrie AG, Konzernarchiv Hanau.',
    image1Source: 'https://www.plexiglas.de/de/ueber-uns/geschichte',
    image2: 'assets/fabrik.png',
    image2Text: 'O. A., Die erste Kunststoffanwendung (um 1928), © Evonik Industrie AG, Konzernarchiv Hanau.',
    image2Source: 'https://www.plexiglas.de/de/ueber-uns/geschichte',
    image3: '',
    image3Source: '',
    image4: '',
    image4Source: '',
    description: 'NOCH AUSSTEHEND',
  },
  {
    name: 'Wetzlar',
    lat: 50.5606,
    lng: 8.5045,
    image1: 'assets/labormann.png',
    image1Text: 'Foto Museum Uhingen, Oskar Barnack an seinem Arbeitsplatz, Fotografie, © Wohlfahrt, Rainer.',
    image1Source: 'https://www.foto-museum-uhingen.de/herzst%C3%BCcke-unserer-sammlung/die-ur-leica-von-1914/',
    image2: 'assets/kamera.png',
    image2Text: 'Wikipedia, Leica I, 1927, Fotografie © Kameraprojekt Graz 2015 / Wikimedia Commons.',
    image2Source: 'https://de.wikipedia.org/wiki/Leica_Camera',
    image3: '',
    image3Source: '',
    image4: '',
    image4Source: '',
    description: 'NOCH AUSSTEHEND',
  },
  {
    name: 'Frankenberg (Eder)',
    lat: 51.0562,
    lng: 8.7961,
    image1: 'assets/stühlebunt.png',
    image1Text: 'Thonet, Bopparder Stuhl, Fotografie, © 2026 Thonet GmbH.',
    image1Source: 'https://www.thonet.de/de/unternehmen/geschichte',
    image2: 'assets/stuhlpaket.png',
    image2Text: 'Thonet, Eine geniale Vertriebsidee, Fotografie, © 2026 Thonet GmbH.',
    image2Source: 'https://www.thonet.de/de/unternehmen/geschichte',
    image3: 'assets/thonet.png',
    image3Text: 'Thonet, Stahlrohrklassiker S 32, Fotografie, © 2026 Thonet GmbH.',
    image3Source: 'https://www.thonet.de/de/unternehmen/geschichte',
    image4: '',
    image4Source: '',
    description: 'NOCH AUSSTEHEND',
  },
  {
    name: 'Melsungen',
    lat: 51.1290,
    lng: 9.5535,
    image1: 'assets/medis.png',
    image1Text: 'Thomas Lemnitzer, Diverse medizintechnische Artikel der Firma B. Braun, Fotografie, 2022, © Hessischer Museumsverband / Projekt "Made in Hessen. Globale Industriegeschichten“.',
    image1Source: 'https://www.made-in-hessen.online/braun/diverse-medizintechnische-artikel-der-firma-b-braun',
    image2: 'assets/desinfektion.png',
    image2Text: 'Thomas Lemnitzer, Desinfektionsmittelspender, Fotografie, © Hessischer Museumsverband / Projekt "Made in Hessen. Globale Industriegeschichten“.',
    image2Source: 'https://www.made-in-hessen.online/setzkasten/desinfektionsmittelspender',
    image3: '',
    image3Source: '',
    image4: '',
    image4Source: '',
    description: 'NOCH AUSSTEHEND',
  },
];
