import { City } from './city.model';

/** Ausgewählte Städte im deutschen Bundesland Hessen. */
export const CITIES: City[] = [
  {
    name: 'Frankfurt am Main',
    lat: 50.1109,
    lng: 8.6821,
    image1: 'assets/img1.jpeg',
    image1Text: 'Skyline von Frankfurt am Main',
    image1Source: 'Pixabay',
    image2: 'assets/img1.jpeg',
    image2Text: 'Der Römerberg im historischen Stadtkern',
    image2Source: 'Pixabay',
    image3: '',
    image3Source: '',
    image4: '',
    image4Source: '',
    description: 'Die größte Stadt Hessens, ein bedeutendes Finanzzentrum und Sitz der Europäischen Zentralbank.',
  },
  {
    name: 'Offenbach am Main',
    lat: 50.0956,
    lng: 8.7761,
    image1: 'assets/img1.jpeg',
    image1Text: 'Blick auf Offenbach am Main',
    image1Source: 'Pixabay',
    image2: 'assets/img1.jpeg',
    image2Text: 'Die Offenbacher Uferpromenade',
    image2Source: 'Pixabay',
    image3: '',
    image3Source: '',
    image4: '',
    image4Source: '',
    description: 'Eine Stadt am Main, traditionell bekannt für ihre Leder- und Modeindustrie.',
  },
  {
    name: 'Kassel',
    lat: 51.3127,
    lng: 9.4797,
    image1: 'assets/img1.jpeg',
    image1Text: 'Der Bergpark Wilhelmshöhe',
    image1Source: 'Pixabay',
    image2: 'assets/img1.jpeg',
    image2Text: 'Die documenta-Stadt Kassel',
    image2Source: 'Pixabay',
    image3: '',
    image3Source: '',
    image4: '',
    image4Source: '',
    description: 'Eine Stadt in Nordhessen, berühmt für den Bergpark Wilhelmshöhe, ein UNESCO-Weltkulturerbe.',
  },
  {
    name: 'Darmstadt',
    lat: 49.8728,
    lng: 8.6512,
    image1: 'assets/img1.jpeg',
    image1Text: 'Die Mathildenhöhe in Darmstadt',
    image1Source: 'Pixabay',
    image2: 'assets/img1.jpeg',
    image2Text: 'Das Darmstädter Schloss',
    image2Source: 'Pixabay',
    image3: '',
    image3Source: '',
    image4: '',
    image4Source: '',
    description: 'Eine Universitäts- und Wissenschaftsstadt, bekannt als "Stadt der Jugendstil-Architektur" (Mathildenhöhe).',
  },
  {
    name: 'Wetzlar',
    lat: 50.5606,
    lng: 8.5045,
    image1: 'assets/img1.jpeg',
    image1Text: 'Die Altstadt von Wetzlar',
    image1Source: 'Pixabay',
    image2: 'assets/img1.jpeg',
    image2Text: 'Der Dom zu Wetzlar an der Lahn',
    image2Source: 'Pixabay',
    image3: '',
    image3Source: '',
    image4: '',
    image4Source: '',
    description: 'Eine Stadt an der Lahn, bekannt für ihre optische Industrie und die historische Altstadt.',
  },
  {
    name: 'Frankenberg (Eder)',
    lat: 51.0562,
    lng: 8.7961,
    image1: 'assets/img1.jpeg',
    image1Text: 'Das Rathaus von Frankenberg',
    image1Source: 'Pixabay',
    image2: 'assets/img1.jpeg',
    image2Text: 'Die Fachwerkhäuser der Altstadt',
    image2Source: 'Pixabay',
    image3: '',
    image3Source: '',
    image4: '',
    image4Source: '',
    description: 'Eine Stadt in Nordhessen mit einem der schönsten Fachwerk-Rathäuser Deutschlands.',
  },
  {
    name: 'Melsungen',
    lat: 51.1290,
    lng: 9.5535,
    image1: 'assets/img1.jpeg',
    image1Text: 'Die Fachwerkstadt Melsungen',
    image1Source: 'Pixabay',
    image2: 'assets/img1.jpeg',
    image2Text: 'Melsungen an der Fulda',
    image2Source: 'Pixabay',
    image3: '',
    image3Source: '',
    image4: '',
    image4Source: '',
    description: 'Eine Kleinstadt an der Fulda, bekannt für ihr Fachwerk und den Medizintechnik-Konzern B. Braun.',
  },
];
